### ISSUE TITLE
User can view a list of notes.

### ISSUE THREAD

**Issue by gdegas** [gdegas/react-notes#1]
# Motivation
User can see all notes in one view

# Tasks
- [x] Create a wireframe
- [x] Add project scaffolding files (package.json, dependencies, scripts, etc.).
- [x] Configure linters
- [x] Create a notes SQL table and add dummy data.
- [x] Create an Express app with a route that serves a JSON list of notes.
- [x] Set up Express static middleware to serve HTML, CSS, and JS.
- [x] Define a NotesList React component that fetches and renders a list of notes.
  - [x] Create a notes.js file
  - [x] In 'notes.js' import React and component and create a class notes
  - [x] Define a method render() and method to fetch notes from data tables.

# Wireframe 

![react-notes-1 gerard](https://user-images.githubusercontent.com/26953295/28838206-8631e018-76a4-11e7-84fd-c3f14db7c294.png)
