### ISSUE TITLE
User can add a note.

### ISSUE THREAD

**Issue by gdegas** [gdegas/react-notes#3]
# Motivation
User can save a note to view later

# Tasks
- [x] Create a wire frame.
- [x] Add a route to the Express app that handles POST requests containing a new note.
  - [x] Npm install body-parser and require it.
  - [x] Define a function that uses knex to insert data into your table.
- [x] Define a form component for accepting new notes.
  - [x] Create new-form.js that exports a function that returns a html data to create a form
- [x] Handle form submissions by sending the new note data to the Express app.
- [x] Ensure that the new note is rendered in the list after it is saved.

# Wireframe

![copy of react-notes-2 gerard](https://user-images.githubusercontent.com/26953295/28849333-6b826608-76cb-11e7-81f8-d2da0a1dd202.png)
