### ISSUE TITLE
User can delete a note.

### ISSUE THREAD

**Issue by gdegas** [gdegas/react-notes#5]
# Motivation
User can delete notes that are no longer needed.

# Tasks
- [x] Add an Express route for deleting a note by its id.
  - [x] In crud-notes.js create a knex query function that takes in an id and deletes that notes
- [x] Enhance NotesList component to send DELETE request to the Express app when a note is clicked.
  - [x] Give the card in render a data-id attribute and set it equal to notes.id
  - [x] Add and onclick event listener to the top div card that passes in the function that fetches for delete.
  - [x] Define a method 'delete note' on the note class that uses event.target.get.data-id for the req.params. id
- [x] Ensure that the note is removed from the view when it has been successfully deleted.
  - [x] In styles.css add a selector for .hidden that sets the display to none.

# Wireframe
![react-notes-3 gerard](https://user-images.githubusercontent.com/26953295/28894157-d2b0983c-7788-11e7-83a0-97c102800958.png)
